networks:
  cms-network:
    driver: bridge
  loki-network:
    driver: bridge

volumes:
  data_opencart-3:
  data_vector:
  data_loki:

include:
  - ./prod/docker-cms-compose.yml
  - ./prod/docker-loki-compose.yml
